### ISSUE TITLE
error NU1102: Unable to find package neo.express with version (= 3.5.19)

### ISSUE THREAD

**Issue by vinayakkalra** [neo-project/neo-blockchain-toolkit#33]
I am getting the below error when execting Run Build Tasks in visual studio code.
I am using MAC M1 to execute this. 

/var/folders/jr/rgwbdwcn75jg35g3fp7_jhfr0000gn/T/5e9a7299-f6ef-4564-8e74-cc8e9557dd31/restore.csproj : error NU1102: Unable to find package neo.express with version (= 3.5.19)
/var/folders/jr/rgwbdwcn75jg35g3fp7_jhfr0000gn/T/5e9a7299-f6ef-4564-8e74-cc8e9557dd31/restore.csproj : error NU1102:   - Found 27 version(s) in nuget.org [ Nearest version: 3.5.20 ]

Package "neo.express" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)

Tool 'neo.compiler.csharp' (version '3.5.0') was restored. Available commands: nccs

Restore partially failed.

 *  The terminal process "/bin/zsh '-c', 'dotnet tool restore'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by cschuchardt88** [comment]
Edit dotnet-tools.json file to 
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "neo.express": {
      "version": "3.5.20",
      "commands": [
        "neoxp"
      ]
    },
    "neo.compiler.csharp": {
      "version": "3.5.0",
      "commands": [
        "nccs"
      ]
    }
  }
}
```

**Also you may have to update Neo.BuildTasks, Neo.Assertions and Neo.Test.Harness  libraries to the 3.5.17 in the project files**
